LoadFile "E:/knrt/knrt-server/cdn/php/libssh2.dll"
LoadFile "E:/knrt/knrt-server/cdn/php/php5ts.dll"
LoadModule php5_module "E:/knrt/knrt-server/cdn/php/php5apache2_4.dll"
<IfModule php5_module>
PHPIniDir "E:/knrt/knrt-server/cdn/php/"
</IfModule>
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
