#server.host = 192.168.20.100
#http server ip and port
http.server.jetty.port = 9001

access.token.timeout = 1800000

#allow ip configure
allow.ips=127.0.0.1/32,192.168.0.1/16,10.162.0.1/16,10.254.93.0/16,10.135.91.245/16,123.207.10.60/16

# database configure
# driver class configure
db.driverClass=com.mysql.jdbc.Driver
# configure of account server
db.account.jdbcUrl=jdbc:mysql://127.0.0.1:3306/user_center?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&rewriteBatchedStatements=true
db.account.username=root
db.account.password=xpymw.com
db.account.idleConnectionTestPeriodInMinutes=60
db.account.idleMaxAgeInSeconds=3600
db.account.maxConnectionsPerPartition=60
db.account.minConnectionsPerPartition=10
db.account.partitionCount=3
db.account.acquireIncrement=5
db.account.statementsCacheSize=256


http.server.recharge.host=127.0.0.1:9880
