Listen 88
<VirtualHost _default_:80>
DocumentRoot "E:/knrt/knrt-server/cdn/www"
  <Directory "E:/knrt/knrt-server/cdn/www">
    Options -Indexes +FollowSymLinks +ExecCGI
    AllowOverride All
    Order allow,deny
    Allow from all
    Require all granted
  </Directory>
</VirtualHost>


<VirtualHost *:88>
    DocumentRoot "E:/knrt/knrt-server/cdn/www"
    ServerName www.gohosts.com
    ServerAlias gohosts.com
  <Directory "E:/knrt/knrt-server/cdn/www">
      Options FollowSymLinks ExecCGI
      AllowOverride All
      Order allow,deny
      Allow from all
     Require all granted
  </Directory>
</VirtualHost>
